# Generated by Django 3.0.3 on 2020-02-09 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seferler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sefer_yeri', models.CharField(max_length=60, verbose_name='Sefer Yeri')),
                ('ucret', models.IntegerField(verbose_name='Ücret')),
                ('musteri', models.CharField(max_length=100, verbose_name='Müşterinin Adı')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('sofor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Şöför')),
            ],
        ),
    ]
