# Generated by Django 3.0.3 on 2020-03-01 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tel_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tbl_firma',
            },
        ),
        migrations.AddField(
            model_name='seferler',
            name='ayar_tarih',
            field=models.DateTimeField(null=True, verbose_name='Transfer Tarih-Saati'),
        ),
        migrations.AddField(
            model_name='seferler',
            name='firma',
            field=models.CharField(max_length=100, null=True, verbose_name='Firma Adı'),
        ),
        migrations.AddField(
            model_name='seferler',
            name='musteri_adress',
            field=models.CharField(max_length=200, null=True, verbose_name='Misafir Adresi'),
        ),
        migrations.AddField(
            model_name='seferler',
            name='musteri_tel',
            field=models.IntegerField(null=True, verbose_name='Misafir Telefon No'),
        ),
        migrations.AddField(
            model_name='seferler',
            name='sofor_pilot',
            field=models.CharField(max_length=30, null=True, verbose_name='Şoför İsmi'),
        ),
        migrations.AlterField(
            model_name='seferler',
            name='musteri',
            field=models.CharField(max_length=100, verbose_name='Misafir Adı'),
        ),
        migrations.AlterField(
            model_name='seferler',
            name='sefer_yeri',
            field=models.CharField(max_length=60, verbose_name='Transfer Yeri'),
        ),
        migrations.AlterField(
            model_name='seferler',
            name='sofor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='seferler',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tel_no', models.CharField(max_length=15)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='expedition.Firma')),
            ],
            options={
                'db_table': 'tbl_musteri',
            },
        ),
    ]
