# Generated by Django 3.0.3 on 2020-02-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seferler',
            name='sefer_yeri',
            field=models.CharField(max_length=60, verbose_name='Transfer Yeri'),
        ),
        migrations.AlterField(
            model_name='seferler',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Transfer Tarihi'),
        ),
    ]
