# Generated by Django 3.0.3 on 2020-02-11 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedition', '0002_auto_20200209_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='seferler',
            name='firma',
            field=models.CharField(max_length=100, null=True, verbose_name="Firma'nın Adı"),
        ),
        migrations.AlterField(
            model_name='seferler',
            name='sofor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Şoför'),
        ),
    ]
