# Generated by Django 3.0.3 on 2020-02-13 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedition', '0004_auto_20200212_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='seferler',
            name='sofor_pilot',
            field=models.CharField(max_length=30, null=True, verbose_name='Şöför İsmi'),
        ),
        migrations.AlterField(
            model_name='seferler',
            name='musteri_adress',
            field=models.CharField(max_length=200, null=True, verbose_name='Müşterinin Adresi'),
        ),
        migrations.AlterField(
            model_name='seferler',
            name='sofor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
    ]
