# Generated by Django 3.0.3 on 2020-02-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0005_auto_20200213_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yıllar', models.CharField(max_length=50, verbose_name='Yıllara göre')),
                ('ic_hatlar', models.CharField(max_length=50, verbose_name='İç Hatlar')),
                ('dıs_hatlar', models.CharField(max_length=50, verbose_name='Dış Hatlar')),
            ],
        ),
    ]
