# Generated by Django 3.0.3 on 2020-02-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0006_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='dıs_hatlar',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='ic_hatlar',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='yıllar',
        ),
        migrations.AddField(
            model_name='chart',
            name='fiyat',
            field=models.CharField(max_length=50, null=True, verbose_name='Fiyat'),
        ),
        migrations.AddField(
            model_name='chart',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Aslı Başlık'),
        ),
        migrations.AddField(
            model_name='chart',
            name='yas',
            field=models.CharField(max_length=50, null=True, verbose_name='Yaşı'),
        ),
    ]
